--ADMIN TABLE CREATE
CREATE TABLE ADMIN(
    USER_NAME VARCHAR(20),
    CONSTRAINT ADMIN_PK PRIMARY KEY(USER_NAME),
    CONSTRAINT ADMIN_GENERAL_USER_FK FOREIGN KEY(USER_NAME) REFERENCES GENERAL_USER
);