-- CATEGORY TABLE CREATE
CREATE TABLE CATEGORY(
    CATEGORY_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
     DESCRIPTION VARCHAR(500),
    CONSTRAINT CATEGORY_PK PRIMARY KEY (CATEGORY_ID)
);