-- DISTRICT TABLE CREATE
CREATE TABLE DISTRICT(
    DISTRICT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    DISTRICT_NAME VARCHAR(20) NOT NULL,
    DELIVERY_COST NUMBER,
    COUNTRY_ID NUMBER NOT NULL,
    CONSTRAINT DISTRICT_DELIVERY_COST_CHK CHECK ( DELIVERY_COST>=0 ),
    CONSTRAINT DISTRICT_PK PRIMARY KEY (DISTRICT_ID),
    CONSTRAINT DISTRICT_COUNTRY_FK FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY
);
