--USER TABLE CREATE
CREATE TABLE GENERAL_USER(
    USER_NAME VARCHAR(20),
    CONSTRAINT GENERAL_USER_PK PRIMARY KEY(USER_NAME),
    PASSWORD VARCHAR(128) NOT NULL,
    CONSTRAINT GENERAL_USER_PASSWORD_CHK CHECK (LENGTH(PASSWORD)>=8 AND REGEXP_LIKE(PASSWORD,'[A-Z]')
    AND REGEXP_LIKE(PASSWORD,'[a-z]')AND REGEXP_LIKE(PASSWORD,'[0-9]') AND
    REGEXP_LIKE(PASSWORD,'[~!@#$%^&*()+=_{}":;|?/.,<>-]')),
    -- TO DO : ADD EMAIL VERIFICATION CONSTRAINT
    EMAIL VARCHAR(320) UNIQUE NOT NULL,
    CONSTRAINT GENERAL_USER_EMAIL_CHK CHECK ( REGEXP_LIKE(EMAIL,'%@%') ),
    PROFILE_PICTURE VARCHAR(30),
    ADDRESS_DESCRIPTION VARCHAR(500),
    FIRST_NAME VARCHAR(15) NOT NULL,
    MIDDLE_NAME VARCHAR(15),
    LAST_NAME VARCHAR(15) NOT NULL,
    NICK_NAME VARCHAR(15),
    ABOUT VARCHAR(500),
    ACCOUNT_CREATE_DATE DATE DEFAULT SYSDATE NOT NULL ,
    PHONE_NUMBER NUMBER,
    USER_SUB_DISTRICT NUMBER,
    CONSTRAINT GENERAL_USER_SUB_DISTRICT_FK FOREIGN KEY(USER_SUB_DISTRICT) REFERENCES SUB_DISTRICT,
    USER_ROLE VARCHAR(15) NOT NULL,
    CONSTRAINT GENERAL_USER_USER_ROLE_CHK CHECK (USER_NAME IN ('CLIENT','ADMIN','DELIVERY_MAN','ASSEMBLER')),
    HAS_ACCOUNT NUMBER DEFAULT 1 NOT NULL
    CONSTRAINT GENERAL_USER_HAS_ACCOUNT_CHK CHECK (HAS_ACCOUNT=0 OR HAS_ACCOUNT=1)
);

ALTER TABLE GENERAL_USER
DROP CONSTRAINT GENERAL_USER_USER_ROLE_CHK;

ALTER TABLE GENERAL_USER
ADD CONSTRAINT GENERAL_USER_USER_ROLE_CHK CHECK (USER_ROLE IN ('CLIENT','ADMIN','DELIVERY_MAN','ASSEMBLER'));

ALTER TABLE GENERAL_USER
DROP CONSTRAINT GENERAL_USER_EMAIL_CHK;
