--ITEM CREATE TABLE
CREATE TABLE ITEM(
    ITEM_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID),
    TITLE VARCHAR(200) UNIQUE NOT NULL,
    PRICE NUMBER NOT NULL,
    CONSTRAINT ITEM_PRICE_CHK CHECK ( PRICE>=0),
    MAIN_IMAGE VARCHAR(210),
    SUMMARY VARCHAR(1000),
    IS_FEATURED NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT ITEM_IS_FEATURED_CHK CHECK ( IS_FEATURED=0 OR IS_FEATURED=1),
    TYPE VARCHAR(10) NOT NULL,
    CONSTRAINT ITEM_TYPE_CHK CHECK ( TYPE IN ('PRODUCT','OFFER')),
    UPDATED_BY VARCHAR(20),
    CONSTRAINT  ITEM_UPDATE_BY_ADMIN_FK FOREIGN KEY(UPDATED_BY) REFERENCES ADMIN,
    UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    IS_CONTINUED NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT ITEM_IS_CONTINUED_CHK CHECK ( IS_CONTINUED=0 OR IS_CONTINUED=1)
);