
--MANUFACTURER TABLE CREATE
CREATE TABLE MANUFACTURER(
    MANUFACTURER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    MANUFACTURER_NAME VARCHAR(100) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(500),
    MOTTO VARCHAR(100),
    LOGO_IMAGE VARCHAR(110),
    IS_VALID NUMBER DEFAULT 1 NOT NULL ,
    CONSTRAINT MANUFACTURER_IS_VALID_CHK CHECK (  IS_VALID=1 OR IS_VALID=0),
    CONSTRAINT MANUFACTURER_PK PRIMARY KEY (MANUFACTURER_ID)
);