CREATE TABLE OFFER_PRODUCTS(
    OFFER_ID NUMBER,
    PRODUCT_ID NUMBER,
    CONSTRAINT OFFER_PRODUCTS_PK PRIMARY KEY(OFFER_ID,PRODUCT_ID),
    CONSTRAINT OFFER_PRODUCTS_OFFER_FK FOREIGN KEY(OFFER_ID) REFERENCES OFFER,
    CONSTRAINT OFFER_PRODUCTS_PRODUCT_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT,
    COUNT NUMBER NOT NULL,
    CONSTRAINT OFFER_PRODUCTS_COUNT_CHK CHECK ( COUNT>0)
);