CREATE TABLE PRODUCT_CONTAINS(
    PARENT_PRODUCT NUMBER,
    CHILD_PRODUCT NUMBER,
    CONSTRAINT PRODUCT_CONTAINS_PK PRIMARY KEY(PARENT_PRODUCT,CHILD_PRODUCT),
    CONSTRAINT PRODUCT_CONTAINS_PARENT_PRODUCT_FK FOREIGN KEY(PARENT_PRODUCT) REFERENCES PRODUCT,
    CONSTRAINT PRODUCT_CONTAINS_CHILD_PRODUCT_FK FOREIGN KEY(CHILD_PRODUCT) REFERENCES PRODUCT
);