-- PRODUCT CREATE
CREATE TABLE PRODUCT(
    ITEM_ID NUMBER,
    CONSTRAINT PRODUCT_PK PRIMARY KEY (ITEM_ID),
    CONSTRAINT PRODUCT_ITEM_FK FOREIGN KEY(ITEM_ID) REFERENCES ITEM,
    STOCK NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PRODUCT_STOCK_CHK CHECK ( STOCK>=0),
    DISCOUNT NUMBER,
    CONSTRAINT PRODUCT_DISCOUNT_CHK CHECK ( DISCOUNT>=0 AND DISCOUNT<=100),
    DISCOUNT_EXPIRE_DATE DATE,
    TUTORIAL_VIDE0 VARCHAR(210),
    THREE_DIM_MODEL VARCHAR(210),
    CATEGORY NUMBER NOT NULL,
    CONSTRAINT PRODUCT_CATEGORY_FK FOREIGN KEY(CATEGORY) REFERENCES CATEGORY,
    MANUFACTURER NUMBER NOT NULL,
    CONSTRAINT PRODUCT_MANUFACTURER_FK FOREIGN KEY(MANUFACTURER) REFERENCES MANUFACTURER
);