--SUB DISTRICT TABLE CREATE
CREATE TABLE SUB_DISTRICT(
    SUB_DISTRICT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    SUB_DISTRICT_NAME VARCHAR(20) NOT NULL,
    DISTRICT_ID NUMBER NOT NULL,
    DELIVERY_SUPPORTED NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT SUB_DISTRICT_PK PRIMARY KEY (SUB_DISTRICT_ID),
    CONSTRAINT SUB_DISTRICT_DISTRICT_FK FOREIGN KEY(DISTRICT_ID) REFERENCES DISTRICT,
    CONSTRAINT SUB_DISTRICT_DELIVERY_SUPPORTED_CHK CHECK ( DELIVERY_SUPPORTED=0 OR DELIVERY_SUPPORTED=1 )
);